---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: fightService
    labels:
        app: fightService
spec:
    replicas: 2
    strategy:
        type: RollingUpdate
    selector:
        matchLabels:
            app: fightService
    template:
        metadata:
            labels:
                app: fightService
        spec:
            containers:
                - name: fightService
                  image: workshop/fightService:jvm:1.1
                  ports:
                      - name: http
                        containerPort: 8080
                  imagePullPolicy: IfNotPresent
                    # To be added:
                  livenessProbe:
                      failureThreshold: 1
                      httpGet:
                          path: /q/health/live
                          port: 8080
                          scheme: HTTP
                      initialDelaySeconds: 0
                      periodSeconds: 5
                      successThreshold: 1
                      timeoutSeconds: 2
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /q/health/ready
                          port: 8080
                          scheme: HTTP
                      initialDelaySeconds: 0
                      periodSeconds: 30
                      successThreshold: 1
                      timeoutSeconds: 10
